"""empty message

Revision ID: fa84e18a0df2
Revises: 
Create Date: 2025-03-23 18:00:21.150880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa84e18a0df2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('message_conversation_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'conversation', ['conversation_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('message_conversation_id_fkey', 'conversation', ['conversation_id'], ['id'])
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
