"""empty message

Revision ID: fcb8fa40b3b3
Revises: fa84e18a0df2
Create Date: 2025-03-23 21:06:13.021141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb8fa40b3b3'
down_revision = 'fa84e18a0df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('github_url')

    # ### end Alembic commands ###
